### ISSUE TITLE
Issue with large XLSX file

### ISSUE THREAD

**Issue by mavaras** [ankane/secure-spreadsheet#1]
Hello everyone.

I'm getting this error while generatin an 12k rows XLSX.
`
(node:6042) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'children' of undefined
    at Cell._parseNode (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Cell.js:608:24)
    at Cell._init (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Cell.js:541:18)
    at new Cell (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Cell.js:24:14)
    at _node.children.forEach.cellNode (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Row.js:352:26)
    at Array.forEach (<anonymous>)
    at Row._init (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Row.js:351:29)
    at new Row (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Row.js:20:14)
    at _sheetDataNode.children.forEach.rowNode (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Sheet.js:1381:25)
    at Array.forEach (<anonymous>)
    at Sheet._init (/nix/store/6i3kkqyrhwd225yxcxqybd2mv6f9rf2z-nodejs-module-secure-spreadsheet/node_modules/xlsx-populate/lib/Sheet.js:1380:38)
(node:6042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6042) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

This just happens with this kind of 'huge' XLSX files. For example, for those with 8k lines there's no problem.
Thanks in advance for any help.

**Comment by ankane** [comment]
Hey @mavaras, secure spreadsheet doesn't support XLS files, only XLSX and CSV.

**Comment by mavaras** [comment]
I meant .xlsx, not .xls, so I think this can be reopen, may I?

**Comment by ankane** [comment]
That's the exact error that's expected for XLS files (https://github.com/dtjohnson/xlsx-populate/issues/269), so my best guess is the file isn't in the XLSX format.

**Comment by ankane** [comment]
fwiw, I just tried on a 65k row by 10 column XLSX file (4 MB) and it worked, so if it's not due to the format, I'm not sure it's related to number of rows.
