### ISSUE TITLE
Unable to create encrypted file

### ISSUE THREAD

**Issue by serkanerdinc** [ankane/secure-spreadsheet#9]
When I try to create I get the following error.

internal/modules/cjs/loader.js:1216
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /root/.nvm/versions/node/v14.4.0/lib/node_modules/secure-spreadsheet/node_modules/get-stdin/index.js
require() of ES modules is not supported.
require() of /root/.nvm/versions/node/v14.4.0/lib/node_modules/secure-spreadsheet/node_modules/get-stdin/index.js from /root/.nvm/versions/node/v14.4.0/lib/node_modules/secure-spreadsheet/src/cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /root/.nvm/versions/node/v14.4.0/lib/node_modules/secure-spreadsheet/node_modules/get-stdin/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:13)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v14.4.0/lib/node_modules/secure-spreadsheet/src/cli.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by jamespavett** [comment]
Getting the exact same error but on Node.js v12.20.1. However only one one of our production servers, the other one is still working just fine. I have tried to compare them both and cannot see any clear differences, so I'm baffled.

Trying to run the following command:

`cat 1609420126-.csv | secure-spreadsheet --password secret > output.xlsx`

And getting the below output:

```
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/lib/node_modules/secure-spreadsheet/node_modules/get-stdin/index.js
require() of ES modules is not supported.
require() of /usr/lib/node_modules/secure-spreadsheet/node_modules/get-stdin/index.js from /usr/lib/node_modules/secure-spreadsheet/src/cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/lib/node_modules/secure-spreadsheet/node_modules/get-stdin/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/secure-spreadsheet/src/cli.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by jamespavett** [comment]
Should add, I'm using the latest available version of the package (1.0.3).

Seems similar to #7 , as this also generated an empty 0kb file.

**Comment by ankane** [comment]
Hey, thanks for the reports. It's due to the new release of `get-stdin` (https://github.com/sindresorhus/get-stdin/releases/tag/v9.0.0). Just pushed a fix to GitHub and will push a new release later today.

**Comment by ankane** [comment]
Version 0.1.4 is out with the fix.

**Comment by jamespavett** [comment]
@ankane any idea why I would have only had this problem on one of my instances? I'm assuming one server was utilising old dependency version but would like to be sure.

**Comment by ankane** [comment]
That'd be my guess.
